events {}

http {
    server {
        listen 80;
        server_name game-platform.local;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name game-platform.local;

        ssl_certificate     /etc/nginx/certs/game-platform.local.pem;
        ssl_certificate_key /etc/nginx/certs/game-platform.local-key.pem;

        location /static/ {
            proxy_pass http://hello:8000/static/;
        }

        location /hello/ {
            proxy_pass http://hello:8000/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
